-- V1 — Baseline do schema.
-- Espelha exatamente o que o Hibernate gerava via ddl-auto=update (capturado com pg_dump),
-- para que spring.jpa.hibernate.ddl-auto=validate passe sem drift.

CREATE TABLE clientes (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf_cnpj  VARCHAR(255),
    email     VARCHAR(255),
    endereco  VARCHAR(255),
    nome      VARCHAR(255),
    telefone  VARCHAR(255)
);

CREATE TABLE produtos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao           VARCHAR(255),
    nome                VARCHAR(255),
    preco_custo         DOUBLE PRECISION,
    preco_venda         DOUBLE PRECISION,
    quantidade_estoque  INTEGER
);

CREATE TABLE servicos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria   VARCHAR(255),
    descricao   VARCHAR(255),
    nome        VARCHAR(255),
    valor_base  DOUBLE PRECISION
);

CREATE TABLE ordem_venda (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda       TIMESTAMP(6) NOT NULL,
    descricao        VARCHAR(255),
    forma_pagamento  VARCHAR(255),
    status           VARCHAR(255),
    valor_total      NUMERIC(10,2) NOT NULL,
    cliente_id       BIGINT NOT NULL,
    CONSTRAINT fk_ordem_venda_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);

-- Obs: produto_id intencionalmente SEM foreign key, espelhando o @NotFound(IGNORE)
-- da entidade ItensVendas (permite item apontar para produto inexistente sem quebrar).
CREATE TABLE itens_vendas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    preco_unitario  NUMERIC(38,2),
    quantidade      INTEGER,
    ordem_venda_id  BIGINT NOT NULL,
    produto_id      BIGINT NOT NULL,
    CONSTRAINT fk_itens_vendas_ordem_venda FOREIGN KEY (ordem_venda_id) REFERENCES ordem_venda (id)
);
