-- V2 — Tabela de veículos. Relação Cliente 1:N Veículo (um cliente tem vários veículos).
-- Base para histórico de instalações, garantia e upgrades. A Task 5 (Ordem de Serviço)
-- vai vincular a OS a um veículo daqui.

CREATE TABLE veiculos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa       VARCHAR(255) NOT NULL,
    marca       VARCHAR(255),
    modelo      VARCHAR(255),
    ano         INTEGER,
    cor         VARCHAR(255),
    cliente_id  BIGINT NOT NULL,
    CONSTRAINT uk_veiculos_placa UNIQUE (placa),
    CONSTRAINT fk_veiculos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);

CREATE INDEX idx_veiculos_cliente_id ON veiculos (cliente_id);
