-- V3 — Estoque fracionado (venda por metro: fio, insulfilm) + Kardex de movimentação.

-- 1) Produto: saldo passa a aceitar fração e ganha unidade de medida
ALTER TABLE produtos
    ALTER COLUMN quantidade_estoque TYPE NUMERIC(12,3) USING quantidade_estoque::numeric(12,3);

ALTER TABLE produtos
    ADD COLUMN unidade_medida VARCHAR(20) NOT NULL DEFAULT 'UN';

-- 2) Itens de venda: quantidade também fracionada (balcão pode vender 2,5 m)
ALTER TABLE itens_vendas
    ALTER COLUMN quantidade TYPE NUMERIC(12,3) USING quantidade::numeric(12,3);

-- 3) Kardex: toda entrada/saída/ajuste de estoque, com saldo resultante (auditável)
CREATE TABLE movimentacao_estoque (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id         BIGINT NOT NULL,
    tipo               VARCHAR(20) NOT NULL,
    quantidade         NUMERIC(12,3) NOT NULL,
    saldo_apos         NUMERIC(12,3) NOT NULL,
    observacao         VARCHAR(255),
    data_movimentacao  TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_movimentacao_estoque_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE INDEX idx_movimentacao_estoque_produto_id ON movimentacao_estoque (produto_id);
