-- V4 — Ordem de Serviço (núcleo): OS + itens (peças consumidas) + serviços (mão de obra com repasse a parceiro)

CREATE TABLE ordem_servico (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id       BIGINT NOT NULL,
    veiculo_id       BIGINT NOT NULL,
    status           VARCHAR(20) NOT NULL,
    descricao        VARCHAR(255),
    data_abertura    TIMESTAMP(6) NOT NULL,
    data_fechamento  TIMESTAMP(6),
    valor_pecas      NUMERIC(12,2),
    valor_servicos   NUMERIC(12,2),
    valor_repasses   NUMERIC(12,2),
    valor_total      NUMERIC(12,2),
    CONSTRAINT fk_os_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id),
    CONSTRAINT fk_os_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos (id)
);

CREATE INDEX idx_os_cliente_id ON ordem_servico (cliente_id);
CREATE INDEX idx_os_veiculo_id ON ordem_servico (veiculo_id);

-- Peças consumidas na OS (baixa no estoque acontece ao finalizar — Task 6)
CREATE TABLE item_os (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id  BIGINT NOT NULL,
    produto_id        BIGINT NOT NULL,
    quantidade        NUMERIC(12,3) NOT NULL,
    preco_unitario    NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_item_os_ordem FOREIGN KEY (ordem_servico_id) REFERENCES ordem_servico (id),
    CONSTRAINT fk_item_os_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE INDEX idx_item_os_ordem_id ON item_os (ordem_servico_id);

-- Mão de obra / serviços da OS, com separação de repasse a parceiro terceirizado
CREATE TABLE servico_os (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id  BIGINT NOT NULL,
    servico_id        BIGINT,
    descricao         VARCHAR(255),
    valor             NUMERIC(12,2) NOT NULL,
    parceiro          VARCHAR(255),
    valor_repasse     NUMERIC(12,2),
    CONSTRAINT fk_servico_os_ordem FOREIGN KEY (ordem_servico_id) REFERENCES ordem_servico (id),
    CONSTRAINT fk_servico_os_servico FOREIGN KEY (servico_id) REFERENCES servicos (id)
);

CREATE INDEX idx_servico_os_ordem_id ON servico_os (ordem_servico_id);
