-- V7 — Financeiro: livro caixa / lançamentos (receitas, despesas, contas a pagar/receber).
-- Alimentado automaticamente pelo PDV e pelo fechamento de OS.

CREATE TABLE lancamento_financeiro (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo              VARCHAR(20) NOT NULL,
    categoria         VARCHAR(30) NOT NULL,
    descricao         VARCHAR(255),
    valor             NUMERIC(12,2) NOT NULL,
    custo             NUMERIC(12,2),
    data              DATE NOT NULL,
    data_vencimento   DATE,
    status            VARCHAR(20) NOT NULL,
    origem            VARCHAR(20) NOT NULL,
    forma_pagamento   VARCHAR(255),
    ordem_venda_id    BIGINT,
    ordem_servico_id  BIGINT
);

CREATE INDEX idx_lancamento_data ON lancamento_financeiro (data);
CREATE INDEX idx_lancamento_status ON lancamento_financeiro (status);
CREATE INDEX idx_lancamento_tipo_status ON lancamento_financeiro (tipo, status);
CREATE INDEX idx_lancamento_ordem_venda ON lancamento_financeiro (ordem_venda_id);
CREATE INDEX idx_lancamento_ordem_servico ON lancamento_financeiro (ordem_servico_id);
