-- V8 — Agenda / Controle de Box: agendamentos por baia, com vínculo opcional a cliente/veículo/OS.

CREATE TABLE agendamento (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    box                INTEGER NOT NULL,
    data_hora_inicio   TIMESTAMP(6) NOT NULL,
    data_hora_fim      TIMESTAMP(6) NOT NULL,
    descricao          VARCHAR(255),
    status             VARCHAR(20) NOT NULL,
    cliente_id         BIGINT,
    veiculo_id         BIGINT,
    ordem_servico_id   BIGINT,
    CONSTRAINT fk_agendamento_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id),
    CONSTRAINT fk_agendamento_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos (id),
    CONSTRAINT fk_agendamento_os FOREIGN KEY (ordem_servico_id) REFERENCES ordem_servico (id)
);

CREATE INDEX idx_agendamento_inicio ON agendamento (data_hora_inicio);
CREATE INDEX idx_agendamento_box ON agendamento (box);
CREATE INDEX idx_agendamento_veiculo ON agendamento (veiculo_id);
